# Generated by Django 4.1.3 on 2022-11-25 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relay_novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relay_novel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='relay_novel',
            name='parent',
        ),
        migrations.AddField(
            model_name='relay_novel',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='relay_novel',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relay_novel',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_novel', to='relay_novel.relay_novel'),
        ),
        migrations.AlterField(
            model_name='relay_novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
